server:
  port: 8084

spring:
  application:
    name: code-graph-engine
  
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j123456

logging:
  level:
    com.poseidon.codegraph.engine.domain.parser: DEBUG
    com.poseidon.codegraph.engine.domain.service.processor: DEBUG

